### ISSUE TITLE
Issue with running programming.

### ISSUE THREAD

**Issue by git4unrealnondev** [rbatis/fast_log#12]
[Archive.zip](https://github.com/rbatis/fast_log/files/9305811/Archive.zip)

Cannot run compile appears to happen on logger flush. Let me know if im doing something wrong.

thread '<unnamed>' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:600:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.62.1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1.62.1/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/1.62.1/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/1.62.1/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/1.62.1/library/core/src/option.rs:1854:5
   5: core::option::Option<T>::expect
             at /rustc/1.62.1/library/core/src/option.rs:718:21
   6: <std::time::SystemTime as core::ops::arith::Sub<core::time::Duration>>::sub
             at /rustc/1.62.1/library/std/src/time.rs:600:9
   7: fastdate::datetime::DateTime::now
   8: <fast_log::appender::FastLogFormat as fast_log::appender::RecordFormat>::do_format
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by zhuxiujia** [comment]
> 

It works fine on my computer

**Comment by git4unrealnondev** [comment]
Yes, I did. 
I am running Arch linux.
I tried it on another linux box and it fails aswell.

**Comment by git4unrealnondev** [comment]
I tried the nightly builds and those had failed aswell. cargo 1.65.0-nightly (ce40690a5 2022-08-09)

**Comment by git4unrealnondev** [comment]
Tried it on a fresh ubuntu 22.04 install and that doesn't work aswell.

**Comment by git4unrealnondev** [comment]
Looks like the fastdate import causes the problem.
Ran cargo test on fastdate git. fails test_date.

warning: `fastdate` (lib test) generated 2 warnings (1 duplicate)
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests src/lib.rs (target/debug/deps/fastdate-5dc670a409cf53ce)

running 5 tests
test date::tests::test_date ... ok
test date::tests::test_ser ... ok
test time::tests::test_from_micros ... ok
test time::tests::test_from_time ... ok
test time::tests::test_date ... FAILED

failures:

---- time::tests::test_date stdout ----
11:12:13.123456
11:12:13.123450
thread 'time::tests::test_date' panicked at 'assertion failed: `(left == right)`
  left: `"11:12:13.012345"`,
 right: `"11:12:13.123450"`', src/time.rs:215:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6/library/core/src/panicking.rs:181:5
   4: fastdate::time::tests::test_date
             at ./src/time.rs:215:9
   5: fastdate::time::tests::test_date::{{closure}}
             at ./src/time.rs:208:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    time::tests::test_date

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass '--lib'

**Comment by git4unrealnondev** [comment]
When you get the chance could you update the cargo.toml file to the latest fastdate version.
Could you push the latest version of fastdate and fast_log to crates.io ?
Many thanks!

**Comment by zhuxiujia** [comment]
> When you get the chance could you update the cargo.toml file to the latest fastdate version. Could you push the latest version of fastdate and fast_log to crates.io ? Many thanks!

you just run ```cargo update```
