### ISSUE TITLE
DEMO 例子运行无打印显示

### ISSUE THREAD

**Issue by yuhaya** [rbatis/fast_log#15]
` use log::{error, info, warn}; 
fn main(){ fast_log::init(Config::new().console()).unwrap(); log::info!("Commencing yak shaving{}", 0); }`

**Comment by yuhaya** [comment]
fast_log是最新的1.5.25,运行例子Demo，控制台无打印信息显示,之前另外一个项目用的1.5.16没有这个问题

**Comment by zhuxiujia** [comment]
> fast_log是最新的1.5.25,运行例子Demo，控制台无打印信息显示,之前另外一个项目用的1.5.16没有这个问题

最新是1.5.35， cargo update 后再试试

**Comment by yuhaya** [comment]
> > fast_log是最新的1.5.25,运行例子Demo，控制台无打印信息显示,之前另外一个项目用的1.5.16没有这个问题
> 
> 最新是1.5.40， cargo update 后再试试

试了一下，更新到1.5.40，控制台还是无法显示打印信息![IMG_20221009_194352.jpg](https://user-images.githubusercontent.com/2966240/194755043-1b50204a-56de-4c61-b7e8-ff3bebf9c695.jpg)
