### ISSUE TITLE
为啥日志输出时必须使用flush才能写/输出日志？

### ISSUE THREAD

**Issue by asins** [rbatis/fast_log#17]
在使用时发现必须在我自己的代码结束时加上一行`log::logger().flush()`才能正常的在控制台或者文件中输出日志，不然无效。
在你的介绍中也看到了这个功能的介绍，但不是所有用户都喜欢这种设定的，也请支持无需要设置flush的日志输出方式。

```rust
use log::LevelFilter;
fn main() {
    fast_log::init(Config::new().console().level(LevelFilter::Info)).unwrap();
    log::info!("----test2---------");
}
```

**Comment by zhuxiujia** [comment]
> 在使用时发现必须在我自己的代码结束时加上一行`log::logger().flush()`才能正常的在控制台或者文件中输出日志，不然无效。 在你的介绍中也看到了这个功能的介绍，但不是所有用户都喜欢这种设定的，也请支持无需要设置flush的日志输出方式。
> 
> ```rust
> use log::LevelFilter;
> fn main() {
>     fast_log::init(Config::new().console().level(LevelFilter::Info)).unwrap();
>     log::info!("----test2---------");
> }
> ```

日志是暂存在channel，等待后台线程批量写磁盘。flush实际上生成了一组WaitGroup等待后台线程执行结束。你不加flush是因为暂存在channel的消息还没等打印你就已经主函数退出了，资源被释放掉了

**Comment by chenfengyuan** [comment]
> ```rust
> .level(LevelFilter::Info)
> ```

It may be better to add a log::logger().flush() in examples.
