### ISSUE TITLE
升级后，没有办法通过 log_path 指定文件名称

### ISSUE THREAD

**Issue by tsxiaofang** [rbatis/fast_log#25]
let buf = Path::new(&file_path);
buf.is_file() 和 buf.is_dir 只有文件或者路径存在时才会返回 true，导致 log_path 带有文件名称时，生成的时路径 log 文件名称为 temp.log

**Comment by zhuxiujia** [comment]
> let buf = Path::new(&file_path); buf.is_file() 和 buf.is_dir 只有文件或者路径存在时才会返回 true，导致 log_path 带有文件名称时，生成的时路径 log 文件名称为 temp.log

确实是一个bug，下个版本修复一下看看

**Comment by zhuxiujia** [comment]
> > let buf = Path::new(&file_path); buf.is_file() 和 buf.is_dir 只有文件或者路径存在时才会返回 true，导致 log_path 带有文件名称时，生成的时路径 log 文件名称为 temp.log
> 
> 确实是一个bug，下个版本修复一下看看

v1.6.5修复这个
