### ISSUE TITLE
不能输出debug日志

### ISSUE THREAD

**Issue by cossonleo** [rbatis/fast_log#3]
请问大佬 无论怎么设置日志等级，都不能输出info以下的日志， 怎么才能输出debug日志

**Comment by zhuxiujia** [comment]
> 请问大佬 无论怎么设置日志等级，都不能输出info以下的日志， 怎么才能输出debug日志

"1.3.8" 版本以及以上，按如下传递日志等级，高到低为Trace，Debug,Info,Warn,Error.   设置的越高输出的越多
```rust
init_custom_log(vec![Box::new(CustomLog {})], 1000, log::Level::Debug, Box::new(NoFilter {}));
```
