### ISSUE TITLE
关于文件日志级别的问题

### ISSUE THREAD

**Issue by moom-en** [rbatis/fast_log#34]
在正式环境中，如何改为Info，但是Error也能输出，而且info跟error分两个文件输入，要能配置文件大小，比如每个文件最大1M，跟java的log4j一样可以配置这些参数呢

**Comment by zhuxiujia** [comment]
> 在正式环境中，如何改为Info，但是Error也能输出，而且info跟error分两个文件输入，要能配置文件大小，比如每个文件最大1M，跟java的log4j一样可以配置这些参数呢

级别设置Info即可

**Comment by moom-en** [comment]
比如我现在设置的文件在info.log中，我想把错误信息输出到error.log中，而不是都输出在info.log中

**Comment by zhuxiujia** [comment]
> 比如我现在设置的文件在info.log中，我想把错误信息输出到error.log中，而不是都输出在info.log中

嗯，那你可以自定义一个结构体，实现 Appender 接口

**Comment by moom-en** [comment]
> > 比如我现在设置的文件在info.log中，我想把错误信息输出到error.log中，而不是都输出在info.log中
> 
> 嗯，那你可以自定义一个结构体，实现 Appender 接口

意思error部分，自己通过创建文件的形式来实现这部分吗？

**Comment by zhuxiujia** [comment]
> > > 比如我现在设置的文件在info.log中，我想把错误信息输出到error.log中，而不是都输出在info.log中
> > 
> > 
> > 嗯，那你可以自定义一个结构体，实现 Appender 接口
> 
> 意思error部分，自己通过创建文件的形式来实现这部分吗？

可以error 的部分，实现一个appender ，然后内部使用 FileSplitAppender 来执行打日志

**Comment by moom-en** [comment]
> > > > 比如我现在设置的文件在info.log中，我想把错误信息输出到error.log中，而不是都输出在info.log中
> > > 
> > > 
> > > 嗯，那你可以自定义一个结构体，实现 Appender 接口
> > 
> > 
> > 意思error部分，自己通过创建文件的形式来实现这部分吗？
> 
> 可以error 的部分，实现一个appender ，然后内部使用 FileSplitAppender 来执行打日志

有没有相关示例呢，我只看到了有customer_appender的示例

**Comment by zhuxiujia** [comment]
> > > > > 比如我现在设置的文件在info.log中，我想把错误信息输出到error.log中，而不是都输出在info.log中
> > > > 
> > > > 
> > > > 嗯，那你可以自定义一个结构体，实现 Appender 接口
> > > 
> > > 
> > > 意思error部分，自己通过创建文件的形式来实现这部分吗？
> > 
> > 
> > 可以error 的部分，实现一个appender ，然后内部使用 FileSplitAppender 来执行打日志
> 
> 有没有相关示例呢，我只看到了有customer_appender的示例

就是它

**Comment by moom-en** [comment]
首页的README最底部的示例代码是错误的

**Comment by zhuxiujia** [comment]
> 首页的README最底部的示例代码是错误的

嗯，可以参考example 文件夹的代码。

**Comment by moom-en** [comment]
> > 首页的README最底部的示例代码是错误的
> 
> 嗯，可以参考example 文件夹的代码。

ok，我开始就是看的这个发现是错的，后边才去看的示例

**Comment by zhuxiujia** [comment]
> > > 首页的README最底部的示例代码是错误的
> > 
> > 
> > 嗯，可以参考example 文件夹的代码。
> 
> ok，我开始就是看的这个发现是错的，后边才去看的示例

```rust
use fast_log::appender::{FastLogRecord, LogAppender};
use fast_log::config::Config;
use fast_log::plugin::file::FileAppender;
use fastdate::DateTime;
use log::Level;

struct InfoAppender {
    file: FileAppender,
}

impl LogAppender for InfoAppender {
    fn do_logs(&mut self, records: &[FastLogRecord]) {
        for record in records {
            let now = DateTime::from(record.now);
            match record.level {
                Level::Error => {}
                Level::Warn => {}
                Level::Info => {
                    self.file.do_logs(records);
                }
                Level::Debug => {}
                Level::Trace => {}
            }
        }
    }
}

fn main() {
    fast_log::init(Config::new().custom(InfoAppender {
        file: FileAppender::new("target/test.log").unwrap(),
    }))
    .unwrap();
    log::info!("Commencing yak shaving");
    log::error!("Commencing error");
    log::logger().flush();
}

```

**Comment by moom-en** [comment]
> > > > 首页的README最底部的示例代码是错误的
> > > 
> > > 
> > > 嗯，可以参考example 文件夹的代码。
> > 
> > 
> > ok，我开始就是看的这个发现是错的，后边才去看的示例
> 
> ```rust
> use fast_log::appender::{FastLogRecord, LogAppender};
> use fast_log::config::Config;
> use fast_log::plugin::file::FileAppender;
> use fastdate::DateTime;
> use log::Level;
> 
> struct InfoAppender {
>     file: FileAppender,
> }
> 
> impl LogAppender for InfoAppender {
>     fn do_logs(&mut self, records: &[FastLogRecord]) {
>         for record in records {
>             let now = DateTime::from(record.now);
>             match record.level {
>                 Level::Error => {}
>                 Level::Warn => {}
>                 Level::Info => {
>                     self.file.do_logs(records);
>                 }
>                 Level::Debug => {}
>                 Level::Trace => {}
>             }
>         }
>     }
> }
> 
> struct ErrorAppender {
>     file: FileAppender,
> }
> 
> impl LogAppender for ErrorAppender {
>     fn do_logs(&mut self, records: &[FastLogRecord]) {
>         for record in records {
>             let now = DateTime::from(record.now);
>             match record.level {
>                 Level::Error => {}
>                 Level::Warn => {}
>                 Level::Info => {
>                     self.file.do_logs(records);
>                 }
>                 Level::Debug => {}
>                 Level::Trace => {}
>             }
>         }
>     }
> }
> 
> fn main() {
>     fast_log::init(
>         Config::new()
>             .custom(InfoAppender {
>                 file: FileAppender::new("target/info.log").unwrap(),
>             })
>             .custom(ErrorAppender {
>                 file: FileAppender::new("target/error.log").unwrap(),
>             }),
>     )
>     .unwrap();
>     log::info!("Commencing yak shaving");
>     log::error!("Commencing error");
>     log::logger().flush();
> }
> ```

谢谢

**Comment by zhuxiujia** [comment]
可以参考我这个实例，只存单个文件，没有做日志轮转。 如果你需要日志按天、或者日志容量轮转，可以改成`file:FileSplitAppender`

**Comment by moom-en** [comment]
> 可以参考我这个实例，只存单个文件，没有做日志轮转。 如果你需要日志按天、或者日志容量轮转，可以改成`file:FileSplitAppender`

好的

**Comment by moom-en** [comment]
> 可以参考我这个实例，只存单个文件，没有做日志轮转。 如果你需要日志按天、或者日志容量轮转，可以改成`file:FileSplitAppender`

`
use fast_log::appender::{FastLogRecord, LogAppender};
use fast_log::consts::LogSize;
use fast_log::plugin::file_split::{FileSplitAppender, KeepType, RawFile, Rolling, RollingType};
use fast_log::plugin::packer::LogPacker;
use fast_log::Config;
use log::{Level, LevelFilter};
use tokio::runtime::Runtime;

pub fn init_fast_log() {
    fast_log::init(
        Config::new()
            .level(if cfg!(debug_assertions) { LevelFilter::Debug } else { LevelFilter::Info })
            .custom(InfoAppender {
                rt: tokio::runtime::Builder::new_multi_thread()
                    .enable_all()
                    .build()
                    .unwrap(),
                file: FileSplitAppender::new::<RawFile>(
                    "logs/info.log",
                    Box::new(Rolling::new(RollingType::BySize(LogSize::MB(1)))),
                    Box::new(KeepType::KeepNum(2)),
                    Box::new(LogPacker {}),
                ).unwrap(),
            })
            .custom(ErrorAppender {
                rt: tokio::runtime::Builder::new_multi_thread()
                    .enable_all()
                    .build()
                    .unwrap(),
                file: FileSplitAppender::new::<RawFile>(
                    "logs/error.log",
                    Box::new(Rolling::new(RollingType::BySize(LogSize::MB(1)))),
                    Box::new(KeepType::KeepNum(2)),
                    Box::new(LogPacker {}),
                ).unwrap(),
            })
            .chan_len(Some(100000))
    ).unwrap();
    log::logger().flush();
}

struct InfoAppender {
    rt: Runtime,
    file: FileSplitAppender,
}
impl LogAppender for InfoAppender {
    fn do_logs(&mut self, records: &[FastLogRecord]) {
        for record in records {
            if record.level == Level::Info {
                self.file.do_logs(records);
            }
        }
    }
}
struct ErrorAppender {
    rt: Runtime,
    file: FileSplitAppender,
}
impl LogAppender for ErrorAppender {
    fn do_logs(&mut self, records: &[FastLogRecord]) {
        for record in records {
            if record.level == Level::Error {
                self.file.do_logs(records);
            }
        }
    }
}
`
这段代码info日志陷入无限循环输出呢，是怎么回事
`
#[actix_web::main]
async fn main() -> ai::Result<()> {
  init_fast_log();
}
`

**Comment by moom-en** [comment]
> > > > 首页的README最底部的示例代码是错误的
> > > 
> > > 
> > > 嗯，可以参考example 文件夹的代码。
> > 
> > 
> > ok，我开始就是看的这个发现是错的，后边才去看的示例
> 
> ```rust
> use fast_log::appender::{FastLogRecord, LogAppender};
> use fast_log::config::Config;
> use fast_log::plugin::file::FileAppender;
> use log::Level;
> 
> struct InfoAppender {
>     file: FileAppender,
> }
> 
> impl LogAppender for InfoAppender {
>     fn do_logs(&mut self, records: &[FastLogRecord]) {
>         for record in records {
>             match record.level {
>                 Level::Error => {}
>                 Level::Warn => {}
>                 Level::Info => {
>                     self.file.do_logs(records);
>                 }
>                 Level::Debug => {}
>                 Level::Trace => {}
>             }
>         }
>     }
> }
> 
> struct ErrorAppender {
>     file: FileAppender,
> }
> 
> impl LogAppender for ErrorAppender {
>     fn do_logs(&mut self, records: &[FastLogRecord]) {
>         for record in records {
>             match record.level {
>                 Level::Error => {}
>                 Level::Warn => {}
>                 Level::Info => {
>                     self.file.do_logs(records);
>                 }
>                 Level::Debug => {}
>                 Level::Trace => {}
>             }
>         }
>     }
> }
> 
> fn main() {
>     fast_log::init(
>         Config::new()
>             .custom(InfoAppender {
>                 file: FileAppender::new("target/info.log").unwrap(),
>             })
>             .custom(ErrorAppender {
>                 file: FileAppender::new("target/error.log").unwrap(),
>             }),
>     )
>     .unwrap();
>     log::info!("Commencing yak shaving");
>     log::error!("Commencing error");
>     log::logger().flush();
> }
> ```

改成 FileSplitAppender 之后，调用 do_logs 函数之后 info 日志陷入无限循环中
