### ISSUE TITLE
手动保存接口

### ISSUE THREAD

**Issue by kuyoonjo** [rbatis/fast_log#6]
有方法在 CTRL+C 时保存未写入的文件吗？还有手动 rotate 的方法。这边希望每日 00:00 的时候 rotate 一下。

**Comment by zhuxiujia** [comment]
> 有方法在 CTRL+C 时保存未写入的文件吗？还有手动 rotate 的方法。这边希望每日 00:00 的时候 rotate 一下。

好主意，我会添加rotate方法
