### ISSUE TITLE
bus error 当使用压缩时使用 flush 方法

### ISSUE THREAD

**Issue by kuyoonjo** [rbatis/fast_log#7]
```rust
    init_split_log(
        "logs/",
        LogSize::MB(100),
        RollingType::KeepNum(10),
        log::Level::Info,
        None,
        Box::new(LZ4Packer {}),
        false,
    ).expect("Failed to init log");
    fast_log::flush().expect("Failed to flush log");
```
`GZipPacker`, `ZipPacker` 会出现 bus error 错误。 `LogPacker` 和 `LZ4Packer` 工作正常。

**Comment by zhuxiujia** [comment]
> ```rust
>     init_split_log(
>         "logs/",
>         LogSize::MB(100),
>         RollingType::KeepNum(10),
>         log::Level::Info,
>         None,
>         Box::new(LZ4Packer {}),
>         false,
>     ).expect("Failed to init log");
>     fast_log::flush().expect("Failed to flush log");
> ```
> 
> `GZipPacker`, `ZipPacker` 会出现 bus error 错误。 `LogPacker` 和 `LZ4Packer` 工作正常。

报错信息贴上来看看

**Comment by kuyoonjo** [comment]
```
hello-tokio (main*) $ target/debug/hello-tokio
[1]    47263 bus error  target/debug/hello-tokio
hello-tokio (main*) $
```

**Comment by kuyoonjo** [comment]
这是所有代码。
```rust
use std::time::Duration;
use fast_log::{consts::LogSize, init_split_log, plugin::packer::LZ4Packer, plugin::{file_split::RollingType}};

fn main() {
    init_split_log(
        "logs/",
        LogSize::MB(100),
        RollingType::KeepNum(10),
        log::Level::Info,
        None,
        Box::new(LZ4Packer {}),
        false,
    ).expect("Failed to init log");

    loop {
        log::info!("Hi fast log");
        fast_log::flush().expect("Failed to flush log");
        std::thread::sleep(Duration::from_secs(1));
    }
}

```

**Comment by zhuxiujia** [comment]
> 这是所有代码。
> 
> ```rust
> use std::time::Duration;
> use fast_log::{consts::LogSize, init_split_log, plugin::packer::LZ4Packer, plugin::{file_split::RollingType}};
> 
> fn main() {
>     init_split_log(
>         "logs/",
>         LogSize::MB(100),
>         RollingType::KeepNum(10),
>         log::Level::Info,
>         None,
>         Box::new(LZ4Packer {}),
>         false,
>     ).expect("Failed to init log");
> 
>     loop {
>         log::info!("Hi fast log");
>         fast_log::flush().expect("Failed to flush log");
>         std::thread::sleep(Duration::from_secs(1));
>     }
> }
> ```

v1.4.1 已修复
