### ISSUE TITLE
怎么样打印出所在的文件行号

### ISSUE THREAD

**Issue by hsyan2008** [rbatis/fast_log#9]
rt

**Comment by zhuxiujia** [comment]
> rt

自定义format
```
fast_log::init(Config::new().format(...).console()).unwrap();
```

**Comment by namespaceYcZ** [comment]
```
fast_log::init(
    Config::new()
        .level(LevelFilter::Trace)
        .format(FastLogFormatByLevel::with_map(default_level_format_map()))
)
.unwrap();
```
其中FastLogFormatByLevel（我随便起的名字）是自定义的struct，需要为它实现RecordFormat这个trait，也就是要实现
`fn do_format(&self, arg: &mut FastLogRecord) -> String`这个函数，其中，FastLogRecord里的line既是行号信息
这里有一个很粗糙的实现，见笑了：
[log_config.rs](https://github.com/rbatis/fast_log/files/9268166/log_config.txt)

**Comment by hsyan2008** [comment]
感谢，已经实现了的，忘了关闭了
